import localFont from "next/font/local";
import ClientProvider from "./client-provider";
import "./globals.css";
import HomePageTopper from "../../components/home-page-componets/home-page-topper"; // Client-side component
import Footer from "../../components/footer";
import Carousel from "../../components/home-page-componets/super-featured-cards";
import SuperFeaturedCards from "../../components/home-page-componets/super-featured-cards";
import ConditionalSuperFeatured from "../../components/home-page-componets/conditional-super-featured";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "In the Loop",
  icons: {
    icon: "/in_the_loop_favicon.png", // Default favicon
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-black not-dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black text-neutral-200`}
      >
        {/* Main container */}
        <main className="relative">
          {/* Carousel */}

          {/* Topper */}
          <header className="absolute top-0 z-[100] w-full">
            <ClientProvider>
              <HomePageTopper />
            </ClientProvider>
          </header>

          {/* Children */}
          <div className="relative z-20 min-h-screen">
            <ClientProvider>{children}</ClientProvider>
          </div>
        </main>
        <Footer />
      </body>
    </html>
  );
}
